Make protocolParams to be standard
StricaHQ/typhonjs pull request #22
Opened 2022-11-10 15:26 UTC by mahnunchik

This PR makes `protocolParams` look like parameters from Cardano GraphQL response.

1. Make number values to be js Number type.
2. Rename `stakeKeyDeposit` to `keyDeposit`
3. Rename `priceSteps` to `priceStep` (ending `s`)
4. Swap values of `priceStep` and `priceMem` according to latest API response.

Docs:
* https://input-output-hk.github.io/cardano-graphql/
* https://graphql-api.testnet.dandelion.link/

2022-11-11 11:07 UTC, ashisherc commented
thank you for this pr @mahnunchik, graphql naming convention is not standard, and hence we will be unable to use that format. It would be ideal to use the cardano-cli output naming convention as it will be maintained in long term. plz see this explanation https://github.com/StricaHQ/typhonjs/issues/5

2022-11-11 11:41 UTC, mahnunchik commented
This PR is related to https://github.com/StricaHQ/typhonjs/issues/21 because `coins/lovelacePerUtxo`**Byte** should be used.

@ashisherc  What do you think about accepting `number` as a parameter or even both `BigNumber`/`number` with internal conversion?

2022-11-12 15:35 UTC, ashisherc requested changes
1. could you please revert the param name changes back to original
2. it is safer to keep Lovelace values as BigNumber, hence also make them BigNumber
3. do you intend to update the minUtxo calculation with this PR? You will need to refer to the new calculation defined by the Cardano node team.

2022-11-14 10:46 UTC, mahnunchik commented
1. Could you please share current output of `cardano-cli query protocol-parameters`. I don't have running node for now.
2. The logic behind the change params to native types is to be able to pass `parameters` as is without conversion to internal BigNumber.
3. I don't understand math of current algorithm yet.

2024-03-05 04:41 UTC, ashisherc commented
https://github.com/StricaHQ/typhonjs/issues/28#issuecomment-1977956876

2024-03-05 04:41 UTC, closed without merging